waypoints:
  wp1: # green box
    position:
      x: -0.5
      y: -2.5
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: -1.0 
      w: 0.0
  wp2: # blue box
    position:
      x: -1.6
      y: 3.5
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: -1.0 
      w: 0.0
  wp3: # red box
    position:
      x: -1.5
      y: 7.5
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: -1.0 
      w: 0.0
  wp4:
    position:
      x: 1.5
      y: 7.5
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0 
      w: 1.0
  wp5:
    position:
      x: 1.5
      y: 0.5
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0 
      w: 1.0
  wp6:
    position:
      x: 2.5
      y: -2.5
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0 
      w: 1.0
